name: CI/CD Pipeline

on:
  push:
    branches:
      - develop # CI triggered on develop branch
      - deploy # CD triggered on deploy branch
  pull_request:
    branches:
      - develop # Run tests on pull requests to develop

jobs:
  # CI job to test code in develop branch
  build:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm install

  # CD job to deploy code from deploy branch to Vercel
  deploy:
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/cli.json
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push image to Docker Hub
        run: |
          docker build -t aammaul7/api-portfolio:latest .
          docker push aammaul7/api-portfolio:latest
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }}
